<?php
// רשימת 63 מסכתות המשנה בסדר המסורתי, עם קישור לטקסט העברי ב-Sefaria-Export (GCS).
// נוצר אוטומטית — ראה database/import_sefaria.php לשימוש.
return [
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Berakhot', 'name_he' => 'ברכות', 'slug' => 'berakhot', 'sefaria_title' => 'Mishnah Berakhot', 'sort_order' => 1],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Peah', 'name_he' => 'פאה', 'slug' => 'peah', 'sefaria_title' => 'Mishnah Peah', 'sort_order' => 2],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Demai', 'name_he' => 'דמאי', 'slug' => 'demai', 'sefaria_title' => 'Mishnah Demai', 'sort_order' => 3],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Kilayim', 'name_he' => 'כלאים', 'slug' => 'kilayim', 'sefaria_title' => 'Mishnah Kilayim', 'sort_order' => 4],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Sheviit', 'name_he' => 'שביעית', 'slug' => 'sheviit', 'sefaria_title' => 'Mishnah Sheviit', 'sort_order' => 5],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Terumot', 'name_he' => 'תרומות', 'slug' => 'terumot', 'sefaria_title' => 'Mishnah Terumot', 'sort_order' => 6],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Maasrot', 'name_he' => 'מעשרות', 'slug' => 'maasrot', 'sefaria_title' => 'Mishnah Maasrot', 'sort_order' => 7],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Maaser Sheni', 'name_he' => 'מעשר שני', 'slug' => 'maaser-sheni', 'sefaria_title' => 'Mishnah Maaser Sheni', 'sort_order' => 8],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Challah', 'name_he' => 'חלה', 'slug' => 'challah', 'sefaria_title' => 'Mishnah Challah', 'sort_order' => 9],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Orlah', 'name_he' => 'ערלה', 'slug' => 'orlah', 'sefaria_title' => 'Mishnah Orlah', 'sort_order' => 10],
    ['seder' => 'zeraim', 'seder_he' => 'זרעים', 'title_en' => 'Bikkurim', 'name_he' => 'ביכורים', 'slug' => 'bikkurim', 'sefaria_title' => 'Mishnah Bikkurim', 'sort_order' => 11],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Shabbat', 'name_he' => 'שבת', 'slug' => 'shabbat', 'sefaria_title' => 'Mishnah Shabbat', 'sort_order' => 12],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Eruvin', 'name_he' => 'עירובין', 'slug' => 'eruvin', 'sefaria_title' => 'Mishnah Eruvin', 'sort_order' => 13],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Pesachim', 'name_he' => 'פסחים', 'slug' => 'pesachim', 'sefaria_title' => 'Mishnah Pesachim', 'sort_order' => 14],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Shekalim', 'name_he' => 'שקלים', 'slug' => 'shekalim', 'sefaria_title' => 'Mishnah Shekalim', 'sort_order' => 15],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Yoma', 'name_he' => 'יומא', 'slug' => 'yoma', 'sefaria_title' => 'Mishnah Yoma', 'sort_order' => 16],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Sukkah', 'name_he' => 'סוכה', 'slug' => 'sukkah', 'sefaria_title' => 'Mishnah Sukkah', 'sort_order' => 17],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Beitzah', 'name_he' => 'ביצה', 'slug' => 'beitzah', 'sefaria_title' => 'Mishnah Beitzah', 'sort_order' => 18],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Rosh Hashanah', 'name_he' => 'ראש השנה', 'slug' => 'rosh-hashanah', 'sefaria_title' => 'Mishnah Rosh Hashanah', 'sort_order' => 19],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Taanit', 'name_he' => 'תענית', 'slug' => 'taanit', 'sefaria_title' => 'Mishnah Ta\'anit', 'sort_order' => 20],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Megillah', 'name_he' => 'מגילה', 'slug' => 'megillah', 'sefaria_title' => 'Mishnah Megillah', 'sort_order' => 21],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Moed Katan', 'name_he' => 'מועד קטן', 'slug' => 'moed-katan', 'sefaria_title' => 'Mishnah Moed Katan', 'sort_order' => 22],
    ['seder' => 'moed', 'seder_he' => 'מועד', 'title_en' => 'Chagigah', 'name_he' => 'חגיגה', 'slug' => 'chagigah', 'sefaria_title' => 'Mishnah Chagigah', 'sort_order' => 23],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Yevamot', 'name_he' => 'יבמות', 'slug' => 'yevamot', 'sefaria_title' => 'Mishnah Yevamot', 'sort_order' => 24],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Ketubot', 'name_he' => 'כתובות', 'slug' => 'ketubot', 'sefaria_title' => 'Mishnah Ketubot', 'sort_order' => 25],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Nedarim', 'name_he' => 'נדרים', 'slug' => 'nedarim', 'sefaria_title' => 'Mishnah Nedarim', 'sort_order' => 26],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Nazir', 'name_he' => 'נזיר', 'slug' => 'nazir', 'sefaria_title' => 'Mishnah Nazir', 'sort_order' => 27],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Sotah', 'name_he' => 'סוטה', 'slug' => 'sotah', 'sefaria_title' => 'Mishnah Sotah', 'sort_order' => 28],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Gittin', 'name_he' => 'גיטין', 'slug' => 'gittin', 'sefaria_title' => 'Mishnah Gittin', 'sort_order' => 29],
    ['seder' => 'nashim', 'seder_he' => 'נשים', 'title_en' => 'Kiddushin', 'name_he' => 'קידושין', 'slug' => 'kiddushin', 'sefaria_title' => 'Mishnah Kiddushin', 'sort_order' => 30],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Bava Kamma', 'name_he' => 'בבא קמא', 'slug' => 'bava-kamma', 'sefaria_title' => 'Mishnah Bava Kamma', 'sort_order' => 31],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Bava Metzia', 'name_he' => 'בבא מציעא', 'slug' => 'bava-metzia', 'sefaria_title' => 'Mishnah Bava Metzia', 'sort_order' => 32],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Bava Batra', 'name_he' => 'בבא בתרא', 'slug' => 'bava-batra', 'sefaria_title' => 'Mishnah Bava Batra', 'sort_order' => 33],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Sanhedrin', 'name_he' => 'סנהדרין', 'slug' => 'sanhedrin', 'sefaria_title' => 'Mishnah Sanhedrin', 'sort_order' => 34],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Makkot', 'name_he' => 'מכות', 'slug' => 'makkot', 'sefaria_title' => 'Mishnah Makkot', 'sort_order' => 35],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Shevuot', 'name_he' => 'שבועות', 'slug' => 'shevuot', 'sefaria_title' => 'Mishnah Shevuot', 'sort_order' => 36],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Eduyot', 'name_he' => 'עדויות', 'slug' => 'eduyot', 'sefaria_title' => 'Mishnah Eduyot', 'sort_order' => 37],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Avodah Zarah', 'name_he' => 'עבודה זרה', 'slug' => 'avodah-zarah', 'sefaria_title' => 'Mishnah Avodah Zarah', 'sort_order' => 38],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Avot', 'name_he' => 'אבות', 'slug' => 'avot', 'sefaria_title' => 'Pirkei Avot', 'sort_order' => 39],
    ['seder' => 'nezikin', 'seder_he' => 'נזיקין', 'title_en' => 'Horayot', 'name_he' => 'הוריות', 'slug' => 'horayot', 'sefaria_title' => 'Mishnah Horayot', 'sort_order' => 40],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Zevachim', 'name_he' => 'זבחים', 'slug' => 'zevachim', 'sefaria_title' => 'Mishnah Zevachim', 'sort_order' => 41],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Menachot', 'name_he' => 'מנחות', 'slug' => 'menachot', 'sefaria_title' => 'Mishnah Menachot', 'sort_order' => 42],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Chullin', 'name_he' => 'חולין', 'slug' => 'chullin', 'sefaria_title' => 'Mishnah Chullin', 'sort_order' => 43],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Bekhorot', 'name_he' => 'בכורות', 'slug' => 'bekhorot', 'sefaria_title' => 'Mishnah Bekhorot', 'sort_order' => 44],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Arakhin', 'name_he' => 'ערכין', 'slug' => 'arakhin', 'sefaria_title' => 'Mishnah Arakhin', 'sort_order' => 45],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Temurah', 'name_he' => 'תמורה', 'slug' => 'temurah', 'sefaria_title' => 'Mishnah Temurah', 'sort_order' => 46],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Keritot', 'name_he' => 'כריתות', 'slug' => 'keritot', 'sefaria_title' => 'Mishnah Keritot', 'sort_order' => 47],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Meilah', 'name_he' => 'מעילה', 'slug' => 'meilah', 'sefaria_title' => 'Mishnah Meilah', 'sort_order' => 48],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Tamid', 'name_he' => 'תמיד', 'slug' => 'tamid', 'sefaria_title' => 'Mishnah Tamid', 'sort_order' => 49],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Middot', 'name_he' => 'מידות', 'slug' => 'middot', 'sefaria_title' => 'Mishnah Middot', 'sort_order' => 50],
    ['seder' => 'kodashim', 'seder_he' => 'קדשים', 'title_en' => 'Kinnim', 'name_he' => 'קינים', 'slug' => 'kinnim', 'sefaria_title' => 'Mishnah Kinnim', 'sort_order' => 51],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Kelim', 'name_he' => 'כלים', 'slug' => 'kelim', 'sefaria_title' => 'Mishnah Kelim', 'sort_order' => 52],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Oholot', 'name_he' => 'אהלות', 'slug' => 'oholot', 'sefaria_title' => 'Mishnah Oholot', 'sort_order' => 53],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Negaim', 'name_he' => 'נגעים', 'slug' => 'negaim', 'sefaria_title' => 'Mishnah Negaim', 'sort_order' => 54],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Parah', 'name_he' => 'פרה', 'slug' => 'parah', 'sefaria_title' => 'Mishnah Parah', 'sort_order' => 55],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Tahorot', 'name_he' => 'טהרות', 'slug' => 'tahorot', 'sefaria_title' => 'Mishnah Tahorot', 'sort_order' => 56],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Mikvaot', 'name_he' => 'מקוואות', 'slug' => 'mikvaot', 'sefaria_title' => 'Mishnah Mikvaot', 'sort_order' => 57],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Niddah', 'name_he' => 'נידה', 'slug' => 'niddah', 'sefaria_title' => 'Mishnah Niddah', 'sort_order' => 58],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Makhshirin', 'name_he' => 'מכשירין', 'slug' => 'makhshirin', 'sefaria_title' => 'Mishnah Makhshirin', 'sort_order' => 59],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Zavim', 'name_he' => 'זבים', 'slug' => 'zavim', 'sefaria_title' => 'Mishnah Zavim', 'sort_order' => 60],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Tevul Yom', 'name_he' => 'טבול יום', 'slug' => 'tevul-yom', 'sefaria_title' => 'Mishnah Tevul Yom', 'sort_order' => 61],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Yadayim', 'name_he' => 'ידיים', 'slug' => 'yadayim', 'sefaria_title' => 'Mishnah Yadayim', 'sort_order' => 62],
    ['seder' => 'tahorot', 'seder_he' => 'טהרות', 'title_en' => 'Oktzin', 'name_he' => 'עוקצין', 'slug' => 'oktzin', 'sefaria_title' => 'Mishnah Oktzin', 'sort_order' => 63],
];
